language: rust
rust:
- stable

sudo: false

cache: cargo

script:
- cargo build --verbose
- cargo build --verbose --features with-rustls
- cargo test --verbose
- cargo test --verbose --features with-rustls