[package]
authors = ["Alena Yuryeva <nimfetrisa@gmail.com>"]
edition = "2018"
name = "pop3-rs"
version = "0.1.0"
[dependencies]
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
regex = "1.1.6"

[dependencies.rustls]
optional = true
version = "0.15.2"

[features]
deafult = ["encryption"]
encryption = ["rustls"]
