[package]
authors = ["Alena Yuryeva <nimfetrisa@gmail.com>"]
edition = "2018"
name = "pop3-rs"
version = "0.1.0"
[dependencies]
log = "0.4.6"

[dependencies.rustls]
optional = true
version = "0.15.2"

[features]
default = ["encryption"]
encryption = ["rustls", "webpki"]

[dependencies.webpki]
version = "0.19.1"
optional = true
