[package]
authors = ["Anton Dutov <anton.dutov@gmail.com>", "Alena Yuryeva <nimfetrisa@gmail.com>"]
description = "Another pop3 client"
edition = "2018"
license = "MIT"
name = "pop3-client"
version = "0.0.1"


[dependencies.rustls]
optional = true
version = "0.15.2"

[dependencies.webpki]
optional = true
version = "0.19.1"

[dependencies.webpki-roots]
optional = true
version = "0.16.0"

[features]
default = []
rustls = ["rustls", "webpki", "webpki-roots"]