[package]
name    = "pop3-client"
edition = "2018"
version = "0.0.1"
license = "MIT"
description = "Another pop3 client"
authors = [
    "Anton Dutov <anton.dutov@gmail.com>",
    "Alena Yuryeva <nimfetrisa@gmail.com>"
]

[features]
default     = []
with-rustls = ["rustls", "webpki", "webpki-roots"]

[dependencies]
log = "0.4.6"

[dependencies.rustls]
optional = true
version = "0.15.2"

[dependencies.webpki]
version = "0.19.1"
optional = true

[dependencies.webpki-roots]
version = "0.16.0"
optional = true
